### PR TITLE
Add support for Config & Diagnostic panels

### LINKED ISSUE #62: Profile dropdown should be under section Configuration
Currently showing under Controls

### PR DESCRIPTION
**Pull request by codyc1515**
Closes #62, #63 & #64

### CODE REVIEW

**Comment by codyc1515** [comment]
May also close #65

**Comment by codyc1515** [comment]
Sorry, looks like this merge got broken somewhere. Please hold off merging this.

**Review by codyc1515 — COMMENTED** [review]
Looks good now.

**Comment by codyc1515** [comment]
Ready to merge. Can you please merge and make a new beta release?

**Comment by Arbuzov** [comment]
Could you please send it into develop?
And fix lint issues :)

**Comment by codyc1515** [comment]
All done :)

**Pull request merged**
